### PR TITLE
Fix File Serialization for Localized Assets

### LINKED ISSUE #129: Asset are not creating File objects for files that are not the default locale
Assets are not properly coercing files in all locales to `Contentful::File` objects, only the default locale.

Example:
```ruby
> asset.instance_variable_get(:@fields)
=> {"en-US"=>
  {:title=>"EN Title",
   :description=>"EN Description",
   :file=>
    #<Contentful::File:0x007fcc52b49aa8
     @content_type="image/svg+xml",
     @details={"size"=>899},
     @file_name="Flag_of_the_United_States.svg",
     @url=
    "//assets.contentful.com/bht13amj0fva/14bZJKTr6AoaGyeg4kYiWq/13f00bdf75c1320061ce471a3881e831/Flag_of_the_United_States.svg">},
 "es"=>
  {:title=>"ES Title",
   :description=>"ES Description",
   :file=>
    {"url"=>
      "//assets.contentful.com/bht13amj0fva/14bZJKTr6AoaGyeg4kYiWq/5501c98c296af77b9acba1146ea3e211/Flag_of_Spain.svg",
     "details"=>{"size"=>60255},
     "fileName"=>"Flag_of_Spain.svg",
     "contentType"=>"image/svg+xml"}}}
```

### PR DESCRIPTION
**Pull request by dlitvakb**
Fixes #129

### CODE REVIEW

File: spec/asset_spec.rb [hunk 1]
```diff
@@ -120,4 +120,26 @@
       end
     end
   end
+
+  describe 'issues' do
```
Comment (jpawlyn) [inline spec/asset_spec.rb]: Instead of `issues`, would say `serialization` be preferable? Just thinking that having loads and loads of issues added here might not be so maintainable.

Comment (dlitvakb) [inline spec/asset_spec.rb]: It's the way I've been dealing with issues, i have a similar section in entries, I like having an issues specific section, in order to keep track of bug fixes

Comment (dlitvakb) [inline spec/asset_spec.rb]: It's easier then to track changelog entries against the test code
